#description: CI pipeline for Yodelr
name: performance-tests
on:
  workflow_run:
    workflows:
      - ci
    types:
      - completed
    branches:
      - main
      - release/**
jobs:
  perftest:
    runs-on: ["ubuntu-latest"]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        words-in-corpus: [100, 1000, 10000, 100000]
    env:
      IMAGE: rxinui/yodelr
      APP_ENV: ci
    steps:
      - uses: actions/checkout@v4

      - name: Update APP_ENV for ci
        run: sed -i -E "s/^(APP_ENV)=.*/\1=${{env.APP_ENV}}/" .env

      - name: Test Yodelr
        continue-on-error: true
        run: make perftest-in-container tag=${{contains(github.ref_name,'/') && 'alpha' || github.ref_name }} psize=${{ matrix.words-in-corpus }}
